AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudOps SnapDeploy Serverless API (Flask in Lambda)

Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    MemorySize: 512

Resources:
  FlaskApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: snapdeploy-backend
      Handler: app.handler
      CodeUri: ./backend
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          STAGE: prod