AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 60

Resources:
  CloudOpsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handler.handler
      Runtime: python3.11
      MemorySize: 1024
      Environment:
        Variables:
          ACCOUNTS_TABLE: snapdeploy-accounts
      Events:
        HttpApiEvent:
          Type: HttpApi